
package com.sltc.soa.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoWS", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "currencyConverter", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverter")
    @ResponseWrapper(localName = "currencyConverterResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CurrencyConverterResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/currencyConverterRequest", output = "http://soa.sltc.com/DemoWS/currencyConverterResponse")
    public float currencyConverter(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exchangeRate", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.ExchangeRate")
    @ResponseWrapper(localName = "exchangeRateResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.ExchangeRateResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/exchangeRateRequest", output = "http://soa.sltc.com/DemoWS/exchangeRateResponse")
    public float exchangeRate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
